"""empty message

Revision ID: 441964995962
Revises: c95d3c95190d
Create Date: 2016-05-17 16:24:00.968529

"""

# revision identifiers, used by Alembic.
revision = '441964995962'
down_revision = 'c95d3c95190d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('dir', sa.Unicode(), nullable=True))
    op.add_column('media', sa.Column('filename', sa.Unicode(), nullable=True))
    op.add_column('media', sa.Column('filesize', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('mimetype', sa.Unicode(), nullable=True))
    op.add_column('media', sa.Column('name', sa.Unicode(), nullable=True))
    op.alter_column('media', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('media', 'name')
    op.drop_column('media', 'mimetype')
    op.drop_column('media', 'filesize')
    op.drop_column('media', 'filename')
    op.drop_column('media', 'dir')
    ### end Alembic commands ###
