"""empty message

Revision ID: c95d3c95190d
Revises: b84c7a707086
Create Date: 2016-05-14 23:25:21.474053

"""

# revision identifiers, used by Alembic.
revision = 'c95d3c95190d'
down_revision = 'b84c7a707086'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relationships', sa.Column('followed_by_id', sa.Integer(), nullable=True))
    op.add_column('relationships', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('unique_idx_user_id_followed_by_id', 'relationships', ['user_id', 'followed_by_id'])
    op.create_foreign_key(None, 'relationships', 'users', ['followed_by_id'], ['id'])
    op.create_foreign_key(None, 'relationships', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_constraint(None, 'relationships', type_='foreignkey')
    op.drop_constraint('unique_idx_user_id_followed_by_id', 'relationships', type_='unique')
    op.drop_column('relationships', 'user_id')
    op.drop_column('relationships', 'followed_by_id')
    ### end Alembic commands ###
